// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeGotThis.Data;

#nullable disable

namespace WeGotThis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929174415_AddQuotes")]
    partial class AddQuotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("WeGotThis.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("WeGotThis.Models.GoalAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("MemberId");

                    b.ToTable("GoalActions");
                });

            modelBuilder.Entity("WeGotThis.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignupIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("WeGotThis.Models.Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGoals")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pool");
                });

            modelBuilder.Entity("WeGotThis.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Marcus Aurelius",
                            Text = "You have power over your mind, not outside events. Realize this, and you will find strength."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Marcus Aurelius",
                            Text = "The impediment to action advances action. What stands in the way becomes the way."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Seneca",
                            Text = "We suffer more often in imagination than in reality."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Seneca",
                            Text = "Luck is what happens when preparation meets opportunity."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Epictetus",
                            Text = "It's not what happens to you, but how you react to it that matters."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Epictetus",
                            Text = "No person is free who is not master of themselves."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Marcus Aurelius",
                            Text = "Waste no more time arguing what a good person should be. Be one."
                        },
                        new
                        {
                            Id = 8,
                            Author = "Seneca",
                            Text = "He who fears death will never do anything worthy of a living person."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Epictetus",
                            Text = "First say to yourself what you would be, then do what you have to do."
                        },
                        new
                        {
                            Id = 10,
                            Author = "Marcus Aurelius",
                            Text = "The best revenge is not to be like your enemy."
                        });
                });

            modelBuilder.Entity("WeGotThis.Models.Goal", b =>
                {
                    b.HasOne("WeGotThis.Models.Member", "Member")
                        .WithMany("Goals")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WeGotThis.Models.GoalAction", b =>
                {
                    b.HasOne("WeGotThis.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeGotThis.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WeGotThis.Models.Member", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
